---
- name: K3s Cluster Installation
  hosts: all
  tasks:
    - name: Installing Components
      ansible.builtin.import_role:
        name: "{{ deploy_type }}"
      loop: "{{ applications }}"
      when: "item.name == {{ 'app' }}"
