---
- name: K3s Cluster Installation
  hosts: all
  tasks:
    - name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
      ansible.builtin.include_vars:
        dir: ../b.roles/application/vars/

    - name: Installing Components
      ansible.builtin.include_role:
        name: "{{ deploy_type }}"
      loop: "{{ applications }}"
      when: "item.name == {{ 'app' }}"
