- name: Including vars file
  include_vars:
    file: /home/annefrank/ansible/b.roles/K3s/tasks/values.yaml

- name: Download and install k3s
  shell: "curl -sfL https://get.k3s.io | sh -s - server {{ ' '.join(k3s_options) }}"
  register: k3s_install_output

- name: Log k3s installation output
  debug:
    msg: "{{ k3s_install_output.stdout }}"
