---
- name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
  ansible.builtin.include_vars:
    dir: vars/

- name: Add Helm repository for
  kubernetes.core.helm_repository:
    name: "{{ item.namespace }}"
    repo_url: "{{ item.repo_url }}"
  loop: "{{ applications }}"
  when: "item.name == {{ 'app' }}"
  
- name: Deploy Helm chart for
  kubernetes.core.helm:
    name: "{{ item.release_name | default(item.chart_ref.split('/')[-1]) }}"
    chart_ref: "{{ item.chart_ref }}"
    release_namespace: "{{ item.namespace }}"
    create_namespace: true
    values: "{{ lookup('template', '../vars/{{ app }}.yaml') | from_yaml }}"
  loop: "{{ applications }}"
  when: "item.name == {{ 'app' }}"
  
  
  
